apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | quote }}
  JWT_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | quote }}
  GROQ_API_KEY: {{ .Values.secrets.GROQ_API_KEY | quote }}
  GROQ_BASE_URL: {{ .Values.secrets.GROQ_BASE_URL | quote }}
  AI_MODEL: {{ .Values.secrets.AI_MODEL | quote }}
  {{- if .Values.secrets.OPENAI_API_KEY }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  {{- end }}
